name: Build Gihub Actions Runner Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/app/keystore.jks

      - name: Create key.properties
        run: |
          cat > android/key.properties << EOF
          storePassword=${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          storeFile=keystore.jks
          EOF

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK arm64-v8a
        run: flutter build apk --release --target-platform android-arm64 --split-per-abi

      - name: Upload APK arm64
        uses: actions/upload-artifact@v4
        with:
          name: GithubRunner-arm64-v8a
          path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk

      - name: Clean up keystore
        if: always()
        run: |
          rm -f android/app/keystore.jks
          rm -f android/key.properties
